baseURL = "https://hardcore-boyd-a29e65.netlify.app/"
languageCode = "en-us"
title = "My Dummy Site"
theme = "m10c"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[params]
[[menu.main]]
name = "Resource Guide"
weight = 1
url = "/DummyRes/"
[[menu.main]]
name = "WordPress Walkthrough"
weight = 3
url = "/DummyWalk/"
[[menu.main]]
name = "Definition Page"
weight = 2
url = "/DummyDef/"
